idf_component_register(
    SRCS
        "app_main.c"
        "b2_config.c"
        "b2_core.c"
        "b2_board.c"
        "b2_relay.c"
        "b2_inputs.c"
        "b2_adc.c"
        "b2_rtc.c"
        "b2_oled.c"
        "b2_modem.c"
        "b2_console.c"
        "b2_onewire.c"
        "b2_storage.c"
        "b2_buttons.c"
        "b2_settings.c"
        "b2_security.c"
        "b2_runtime.c"
        "b2_eventlog.c"
        "b2_rules.c"
        "b2_modbus.c"
        "b2_wifi.c"
        "b2_mqtt.c"
        "b2_http.c"
        "b2_tls_credentials.c"
        "b2_ble.c"
        "b2_ota.c"
        "b2_time.c"
        "b2_cellular.c"
        "b2_ethernet.c"
        "b2_i2c_expander.c"
    INCLUDE_DIRS
        "."
        "include"
    REQUIRES
        driver
        bt
        esp_event
        esp_netif
        esp_eth
        esp_wifi
        mqtt
        esp_http_server
        esp_https_ota
        esp_https_server
        esp_modem
        app_update
        fatfs
        nvs_flash
        sdmmc
        esp_timer
        freertos
        log
        json
)
